//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitaplar
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitabım
    {
        public int Id { get; set; }
        public string kit_adi { get; set; }
        public string kit_yazar { get; set; }
        public string okundu_bilgisi { get; set; }
    }
}
